server:
  port: ${PORT:8083}

spring:
  application:
    name: ai-chatbot

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000
      data-source-properties:
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

brevo:
  api:
    key: ${BREVO_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000

gemini:
  api:
    key: ${GEMINI_API_KEY}